[package]
name = "sunwalker_box"
version = "0.1.0"
edition = "2021"
authors = ["Ivanq <imachug@gmail.com>"]
license = "GPL-3.0-or-later"
description = "Sandbox for sunwalker judge system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.6", features = ["derive"] }
interfaces = "0.0.8"
json = "0.12.4"
libc = "0.2.120"
multiprocessing = { path = "multiprocessing" }
nix = "0.23.1"
openat = "0.1.21"
rand = "0.8.5"

[profile.release]
strip = true
lto = true
